import messageStyles from '../../styles/shared.module.css';
import styles from './LLMMessage.module.css';

const LLMMessage = () => {
    return (
        <div className={`${messageStyles.chatMessage} ${styles.llmMessage}`}>
            Test message generated by the LLM.
        </div>
    );
};

export default LLMMessage;
